### ISSUE TITLE
Gradle is not pulling

### ISSUE THREAD

**Issue by mfhassan22** [felixsoares/HorizontalBarGraph#1]
```
dependencies {
	compile 'com.github.felixsoares:HorizontalBarGraph:1.0'
}
```
**Not retrieving the repository can you check this. i have tried a lot but unable to find the reason**

**Comment by felixsoares** [comment]
are you put this in your build.gradle?

allprojects {
   repositories {
        maven { url 'https://jitpack.io' }
   }
}

**Comment by mfhassan22** [comment]
I switched to another library
